//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweeTron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receita()
        {
            this.Possui = new HashSet<Possui>();
            this.Solicita = new HashSet<Solicita>();
            this.Passo = new HashSet<Passo>();
        }
    
        public int ID_Receita { get; set; }
        public double Rating { get; set; }
        public string Dificuldade { get; set; }
        public string Nome { get; set; }
        public int Duracao { get; set; }
        public string Preparacao { get; set; }
        public string Video { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Possui> Possui { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicita> Solicita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passo> Passo { get; set; }
    }
}
