//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweeTron.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicita
    {
        public int ID_Utilizador { get; set; }
        public int ID_Receita { get; set; }
        public Nullable<int> Avaliacao { get; set; }
        public Nullable<bool> Favorito { get; set; }
        public string Comentario { get; set; }
    
        public virtual Receita Receita { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
