//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweeTron.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SweeTronEntities : DbContext
    {
        public SweeTronEntities()
            : base("name=SweeTronEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingrediente> Ingrediente { get; set; }
        public virtual DbSet<Passo> Passo { get; set; }
        public virtual DbSet<Possui> Possui { get; set; }
        public virtual DbSet<Receita> Receita { get; set; }
        public virtual DbSet<Solicita> Solicita { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
    }
}
